services:
  web:
    build:
      context: web
    ports:
      - 3000:3000

  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGUSER: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
